### ISSUE TITLE
Can't get Reforged placeholders to work in overlay

### ISSUE THREAD

**Issue by griffindeed** [Pixelmon-Development/PixelmonOverlay-Forge#3]
Can't seem to get the Reforged placeholders to work. Forge placeholders work and the reforged extension is installed.
fpapi: 2.0.4
reforged extension: 2.9.1
Overlay: 1.0.0
(All 1.16.5)
![image](https://user-images.githubusercontent.com/7983016/180631261-396f9af2-0f99-4bbc-a85d-9317895d0edb.png)
Config:
`
    three:
        layout-type: LEFT_AND_RIGHT
        text:
        - '§6 %forge_displayname% %reforged_dex_percentage% %reforged_nextlegendary%
            %forge_tps%'
        - '§a %reforged_wins% %reforged_losses% %reforged_wl_ratio%'
        duration-seconds: 30
        config-data:
            __class__: com.envyful.pixelmon.overlay.forge.config.type.PixelmonConfigData
            spec: umbreon
            sprite: true`

**Comment by johnfriedrich** [comment]
You need to use the correct reforged Prefix. See wiki. (reforged16) if I remember correctly

**Comment by griffindeed** [comment]
Ahh, that did the trick. Thank you!
