### ISSUE TITLE
Problem when want see pokemon in gui

### ISSUE THREAD

**Issue by GoldenGuys** [Pixelmon-Development/PixelmonOverlay-Forge#5]
Hello i have installed the side-mod Reforged Bingo, and when i click on pokemon card i receive in chat "/pwiki  command don't exist" do u know why the command /pwiki don't exist and if i need install an specific dependency ?

"Unknown or incomplete command. see error below"
![image](https://user-images.githubusercontent.com/122744879/213259465-6bc2f887-6025-4c99-979a-10637575b5db.png)

**Comment by danorris709** [comment]
This has nothing to do with Overlays
